add file

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -56,17 +56,17 @@ jobs:
       - name: run alert dependencies
         run: python3 ./actions/dependency-scan/slack-alert.py ${{ secrets.SLACK_WEBHOOK}}
 
-      # - name: check failure
-      #   if: steps.secret.outcome != 'success' || steps.dependencies.outcome != 'success'
-      #   run: exit 1
       - name: check failure
-        if: steps.dependencies.outcome != 'success'
+        if: steps.secret.outcome != 'success' || steps.dependencies.outcome != 'success'
         run: exit 1
+      # - name: check failure
+      #   if: steps.dependencies.outcome != 'success'
+      #   run: exit 1
 
 
   deploy:
-    if: github.event.review.state == 'approved'
     needs: security
+    if: github.event.review.state == 'approved'
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
