add file

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -53,8 +53,11 @@ jobs:
       - name: run alert dependencies
         run: python3 ./actions/dependency-scan/slack-alert.py ${{ secrets.SLACK_WEBHOOK}}
 
+      # - name: check failure
+      #   if: steps.secret.outcome != 'success' || steps.dependencies.outcome != 'success'
+      #   run: exit 1
       - name: check failure
-        if: steps.secret.outcome != 'success' || steps.dependencies.outcome != 'success'
+        if: steps.dependencies.outcome != 'success'
         run: exit 1
 
 
